export enum AuctionStatus {
    SinEstatus = 1, 
    Activa = 2,    
    Finalizada = 3,
    MinimoNoAlcanzado = 1021,
    PropuestaGanador = 4,
    PropuestaVendedor = 1022,
    RechazoGanador = 5,
    // AceptadoGanador = 6, 
    // PropuestaSiguiente = 7,    
    // AceptadoSiguiente = 8,
    // RechazadoSiguiente = 9,
    NoEfectuada = 10,
    PendientePago = 12,    
    Pagado = 11, 
    PreparacionEnvio = 13,
    Enviado = 14,
    Recibido = 15,
    RecepcionCorrecta = 1023,
    Reclamo = 1024,
    Rechazada = 1016,
    PorAprobar = 17
  }